version: '3.9'

services:

    orders-db:
        image: postgres:latest
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=orders_db
        command: ["postgres", "-c", "logging_collector=on", "-c", "log_statement=all"]